- api
- fitur create user baru di halaman admin
- source js css untuk diakses offline
- js select2
- js datatable, fitur search, order, paginasi
- membedakan crud user biasa dengan admin 
- restriksi user yang berusaha akses paksa (mengetik langsung di kolom url) dengan menggunakan middleware
- modal konfirmasi hapus
- modal notifikasi tindakan sukses/gagal
- trigger modal dengan id javascript agar tidak looping kodingannya
- fitur user memesan 2 kolam renang dalam 1 order